---
stages:
  - lint

lint:yaml:
  stage: lint
  image: python:buster
  script: |
    test -f requirements.txt && pip install -r requirements.txt
    yamllint -c .yamllint.yml .
  interruptible: true
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  tags:
    - docker

lint:dockerfile:
  stage: lint
  image: "hadolint/hadolint:${HADOLINT_VERSION}"
  script: |
    hadolint -v
    [[ -f "${HADOLINT_CONFIG}" ]] && CONFIG_OPT="-c ${HADOLINT_CONFIG}" || CONFIG_OPT="";
    hadolint -V $CONFIG_OPT $(find -iname Dockerfile)
  interruptible: true
  variables:
    HADOLINT_VERSION: 2.5.0-alpine
    HADOLINT_CONFIG: hadolint.yaml
  tags:
    - docker
