---
stages:
  - lint
  - registry

include:
  - local: '/.gitlab-ci/docker.yml'

# stage: lint

lint:yaml:
  stage: lint
  image: python:buster
  script: |
    test -f requirements.txt && pip install -r requirements.txt
    yamllint -c .yamllint.yml .
  interruptible: true
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  tags:
    - docker

lint:docker:
  stage: lint
  extends:
    - .docker-lint

# stage: registry

registry:
  stage: registry
  extends:
    - .docker-registry
  needs:
    - job: lint:docker
      artifacts: false
  only:
    - master
  parallel:
    matrix:
      - DOCKER_TAG_PREFIX: jdk-11-
        DOCKER_FILE: jdk-11/Dockerfile
      - DOCKER_TAG_PREFIX: jdk-8-
        DOCKER_FILE: jdk-8/Dockerfile
  variables:
    DOCKER_REGISTRY: "${DOCKER_HUB_REGISTRY}"
    DOCKER_REGISTRY_USER: "${DOCKER_HUB_REGISTRY_USER}"
    DOCKER_REGISTRY_PASSWORD: "${DOCKER_HUB_REGISTRY_PASSWORD}"
    DOCKER_REGISTRY_IMAGE: index.docker.io/raatiniemi/android-environment
