---
stages:
  - lint

lint:yaml:
  stage: lint
  image: python:buster
  script: |
    test -f requirements.txt && pip install -r requirements.txt
    yamllint -c .yamllint.yml .
  interruptible: true
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  tags:
    - docker

lint:dockerfile:
  stage: lint
  image: hadolint/hadolint:2.5.0-alpine
  script: |
    hadolint $(find -iname Dockerfile)
  interruptible: true
  tags:
    - docker
