---
include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Checkov.gitlab-ci.yml'
      - '/templates/Docker.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'
  - project: 'rahome/trivy-cache'
    ref: main
    file:
      - '/Trivy.gitlab-ci.yml'

lint:docker:
  extends:
    - .docker-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

lint:yaml:
  extends:
    - .yaml-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

prepare-sdk-artifacts:
  image: alpine:3.16.0
  before_script:
    - apk -qU --no-cache add curl unzip ca-certificates
  script: |
    curl -O -Ls "https://dl.google.com/android/repository/${ANDROID_CMDLINE_TOOLS_ZIP}"
    unzip -qq "${ANDROID_CMDLINE_TOOLS_ZIP}"
    mkdir -p "${ANDROID_HOME}/cmdline-tools"
    mv cmdline-tools "${ANDROID_HOME}/cmdline-tools/latest"
  artifacts:
    paths:
      - "${ANDROID_HOME}"
  variables:
    ANDROID_HOME: /opt/android-sdk
    ANDROID_CMDLINE_TOOLS_ZIP: commandlinetools-linux-8092744_latest.zip

registry:
  extends:
    - .docker-registry
  needs:
    - job: lint:docker
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  parallel:
    matrix:
      - JDK_VERSION: "jdk-8"
        DOCKER_FILE: "${JDK_VERSION}/Dockerfile"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-"
        DOCKER_FILE: "${JDK_VERSION}/Dockerfile"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        ANDROID_API_VERSION: [28, 29, 30, 31, 32, 33]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-android-${ANDROID_API_VERSION}-"
        DOCKER_FILE: "${JDK_VERSION}/${ANDROID_API_VERSION}/Dockerfile"
  variables:
    DOCKER_REGISTRY: "${DOCKER_HUB_REGISTRY}"
    DOCKER_REGISTRY_USER: "${DOCKER_HUB_REGISTRY_USER}"
    DOCKER_REGISTRY_PASSWORD: "${DOCKER_HUB_REGISTRY_PASSWORD}"
    DOCKER_REGISTRY_IMAGE: index.docker.io/raatiniemi/android-environment

sast:checkov:
  extends:
    - .checkov-junit
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success
  parallel:
    matrix:
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        DOCKER_FILE: "${JDK_VERSION}/Dockerfile"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        ANDROID_API_VERSION: [28, 29, 30, 31, 32, 33]
        DOCKER_FILE: "${JDK_VERSION}/${ANDROID_API_VERSION}/Dockerfile"
  variables:
    CHECKOV_COMMAND: "-f ${DOCKER_FILE}"

sast:trivy:
  extends:
    - .trivy
  allow_failure: true
  needs:
    - job: registry
      optional: true
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  parallel:
    matrix:
      - JDK_VERSION: "jdk-8"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        ANDROID_API_VERSION: [28, 29, 30, 31, 32, 33]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-android-${ANDROID_API_VERSION}-"
  variables:
    TRIVY_AUTH_URL: "${DOCKER_HUB_REGISTRY}"
    TRIVY_USERNAME: "${DOCKER_HUB_REGISTRY_USER}"
    TRIVY_PASSWORD: "${DOCKER_HUB_REGISTRY_PASSWORD}"
    CI_REGISTRY_IMAGE: index.docker.io/raatiniemi/android-environment
