---
stages:
  - lint
  - registry

include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Docker.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'

# stage: lint

lint:docker:
  stage: lint
  extends:
    - .docker-lint

lint:yaml:
  stage: lint
  extends:
    - .yaml-lint

# stage: registry

registry:
  stage: registry
  extends:
    - .docker-registry
  needs:
    - job: lint:docker
      artifacts: false
  only:
    refs:
      - master
    changes:
      - "${DOCKER_FILE}"
  parallel:
    matrix:
      - JDK_VERSION: "jdk-8"
        DOCKER_FILE: "${JDK_VERSION}/Dockerfile"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-"
        DOCKER_FILE: "${JDK_VERSION}/Dockerfile"
      - JDK_VERSION: ["jdk-11", "jdk-8"]
        ANDROID_API_VERSION: [28, 29, 30]
        DOCKER_TAG_PREFIX: "${JDK_VERSION}-android-${ANDROID_API_VERSION}-"
        DOCKER_FILE: "${JDK_VERSION}/${ANDROID_API_VERSION}/Dockerfile"
  variables:
    DOCKER_REGISTRY: "${DOCKER_HUB_REGISTRY}"
    DOCKER_REGISTRY_USER: "${DOCKER_HUB_REGISTRY_USER}"
    DOCKER_REGISTRY_PASSWORD: "${DOCKER_HUB_REGISTRY_PASSWORD}"
    DOCKER_REGISTRY_IMAGE: index.docker.io/raatiniemi/android-environment
