---
# yamllint disable rule:line-length
.docker-lint:
  image: "hadolint/hadolint:${HADOLINT_VERSION}"
  script: |
    hadolint -v
    [[ -f "${HADOLINT_CONFIG}" ]] && CONFIG_OPT="-c ${HADOLINT_CONFIG}" || CONFIG_OPT="";
    hadolint -V $CONFIG_OPT $(find -iname Dockerfile)
  interruptible: true
  tags:
    - docker
  variables:
    HADOLINT_VERSION: 2.5.0-alpine
    HADOLINT_CONFIG: hadolint.yaml

.docker-registry:
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - mkdir -p /root/.docker
    - echo "${DOCKER_REGISTRY_PASSWORD}" | docker login -u "${DOCKER_REGISTRY_USER}" --password-stdin "${DOCKER_REGISTRY}"
  script: |
    docker pull "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}latest" || true
    docker build --cache-from "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}latest" --tag "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" -f "${DOCKER_FILE}" .
    docker tag "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}latest"
    docker push "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}latest"
    if [ -n "${CI_COMMIT_TAG}" ]; then
      docker tag "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}${CI_COMMIT_TAG}"
      docker push "${DOCKER_REGISTRY_IMAGE}:${DOCKER_TAG_PREFIX}${CI_COMMIT_TAG}"
    fi;
  after_script:
    - docker logout "${DOCKER_REGISTRY}"
    - rm -rf /root/.docker
  tags:
    - docker-cli
  variables:
    DOCKER_REGISTRY: "${CI_REGISTRY}"
    DOCKER_REGISTRY_USER: "${CI_REGISTRY_USER}"
    DOCKER_REGISTRY_PASSWORD: "${CI_REGISTRY_PASSWORD}"
    DOCKER_REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
    DOCKER_TAG_PREFIX: ""
    DOCKER_FILE: "Dockerfile"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
# yamllint enable rule:line-length
